# NUMPY

### Numpy multiplication

In [5]:
import numpy as np

lst = [2, 4, 6]

array = np.array(lst)
result = array * 2

print(result)




[ 4  8 12]


### Numpy addition


In [ ]:
import numpy as np

lst=[2,4,5]
lst1=[2,4,5]
array1=np.array(lst)
array2=np.array(lst1)
result=array1+array2
print(result) 

[ 4  8 10]


### Numpy Substraction


In [8]:
import numpy as np

lst=[2,3,5]
lst1=[2,4,5]
array1=np.array(lst)
array2=np.array(lst1)
result=array1-array2
print(result)


[ 0 -1  0]


### Numpy division

In [9]:
import numpy as np


lst = [2, 4, 6]

array = np.array(lst)
result = array//2

print(result)


[1 2 3]


# Scalar arithmetic operation

In [ ]:
import numpy as np

#Mathematical operation in a single line

array=np.array([1,2,3,4,5])

print(array+1)
print(array-1)
print(array//1)
print(array*2)
print(array**2)
print(array**3)


[2 3 4 5 6]
[0 1 2 3 4]
[1 2 3 4 5]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[  1   8  27  64 125]


# Vector Arithmetic operation

In [16]:
import numpy as np


array = np.array([1,2,3,4,5])
array1=np.array([1.2,2.2,3.3,4.4,5.6])
print(np.sqrt(array))
print(np.round(array1))
print(np.floor(array1))
print(np.pi)


[1.         1.41421356 1.73205081 2.         2.23606798]
[1. 2. 3. 4. 6.]
[1. 2. 3. 4. 5.]
3.141592653589793


# matrice multiplication

### 2D Array

In [ ]:
import numpy as np

A=np.array([[1,2],
            [2,3]])

B=np.array([[2,3],
            [7,8]])

print(A.shape)#array dimension
print(A*B)

(2, 2)
[[ 2  6]
 [14 24]]


# indexing

## index value number

In [21]:
lst=[[[1,2,3],[2,4,5],[3,4,5]]]
print(lst[0][1][1])

4


In [28]:
import numpy as np

lst = np.array([[[1, 2, 3],
                 [2, 4, 5],
                 [3, 4, 5]]])

print(lst[0][0])

[1 2 3]


# index dimension check

In [30]:
import numpy as np

lst = np.array([[[1, 2, 3],
                 [2, 4, 5],
                 [3, 4, 5]]])

print(lst.ndim)

3


In [31]:
import numpy as np

lst = np.array([[[1, 2, 3],
                 [2, 4, 5],
                 [3, 4, 5]]])

print(lst.shape)

(1, 3, 3)


# Addition

In [36]:
import numpy as np

lst = np.array([[[1, 2, 3],
                 [2, 4, 5],
                 [3, 4, 5]]])

print(lst[0]+[1])

[[2 3 4]
 [3 5 6]
 [4 5 6]]


# 3D multiplication nested list

In [40]:
import numpy as np

lst=[[1,2,3],[3,4,5],[4,5,6]]
result=np.array(lst)
result=result*5
print(result)

[[ 5 10 15]
 [15 20 25]
 [20 25 30]]


In [41]:
import numpy as np

lst=[[1,2,3],[3,4,5],[4,5,6]]

result=np.array(lst)
print(lst[0]+lst[1])



[1, 2, 3, 3, 4, 5]


# slice


In [55]:
import numpy as np

lst=[1,2,3,4,5,6,7,8]
result=np.array(lst)

print(lst[1:8])

[2, 3, 4, 5, 6, 7, 8]


In [48]:
import numpy as np

lst=[1,2,3,4,5,6,7,8]
result=np.array(lst)

print(lst[1:])

[2, 3, 4, 5, 6, 7, 8]


In [51]:
import numpy as np

lst=[1,2,3,4,5,6,7,8]
result=np.array(lst)

print(lst[:-1])

[1, 2, 3, 4, 5, 6, 7]


# Negative slicing

In [53]:
import numpy as np

lst=np.array([1,2,3,4,5,6,7,8])
print(lst[-3:-1])


[6 7]


# print every 3rd element


In [54]:
import numpy as np

lst=np.array([1,2,3,4,5,6,7,7])
print(lst[::3])

[1 4 7]


# slicing 2D

## Row slicing

In [56]:
import numpy as np

lst=np.array([[1,2,3,4,5,6,7],
              [2,4,5,6,7,8,8]])

print(lst[0,0:4])



[1 2 3 4]


## coloumn slicing

In [57]:
import numpy as np

lst=np.array([[1,2,3,4,5,6,7],
              [2,4,5,6,7,8,8]])

print(lst[0:2,1])


[2 4]


In [61]:
import numpy as np
lst=np.array([[1,2,3,4,5,6,7],
              [2,4,5,6,7,8,8]])

print(lst[0:2, 1:4])



[[2 3 4]
 [4 5 6]]


# matrix multiplication

##### Matrix multiplication is how the network learns and transforms data.Matrix multiplication is used in AI to combine many input features with weights at once to produce outputs — this is how neural networks make predictions.This is how a neural network layer works:inputs × weights → outputs

In [2]:
import numpy as np

A= np.array([[3,4],
            [5,4]])

B=np.array([[5,6],
            [7,6]])

print(np.matmul(A,B))

[[43 42]
 [53 54]]


In [3]:
import numpy as np

A= np.array([[3,4],
            [5,4]])

B=np.array([[5,6],
            [7,6]])

print(A@B)

[[43 42]
 [53 54]]


In [4]:
import numpy as np

A= np.array([[3,4],
            [5,4]])

B=np.array([[5,6],
            [7,6]])

print(A.dot(B))

[[43 42]
 [53 54]]


## 1*3 3*2 multiplication

In [6]:
import numpy as np

X = np.array([[150,65,20]])#1*3 weights
W = np.array([[0.2,1.4],
             [2.2,3.4],
             [0.3,3.4]])
#3*2
output = X@W
print(output)

#array1=(m*n)-->(1*3)
#array1=(n*p)-->(3*2)
#no of coloumn in first numpy array=no of rows in a second numpy array

[[179. 499.]]


# Concatenation

### combing two array

### Row wise

In [ ]:
import numpy as np

A=np.array([[1,2,3]])
B=np.array([[4,5,6]])
c=np.concatenate((A,B),axis=0) #row-wise
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


### Coloumn wise

In [9]:
import numpy as np

A=np.array([[1,2,3]])
B=np.array([[4,5,6]])
c=np.concatenate((A,B),axis=1) #coloumn wise
print(c)

[[1 2 3 4 5 6]]


# Aggregate Function in numpy

#####   Aggregate functions are used to summarize data.They usually take an array as input and return a single value (or summary).Examples: sum, mean, max, min, argmin, argmax, etc.

### Sum

In [11]:
import numpy as np

array=np.array([[1,3,4,5,6],
                [2,3,4,5,5]])

print("sum of elements:",np.sum(array))

sum of elements: 38


### Mean

In [12]:
import numpy as np

array=np.array([[1,3,4,5,6],
                [2,3,4,5,5]])

print("Average :",np.mean(array))

Average : 3.8


### Minimum value and maximum value of elements 
### index Minimum value and index maximum value of elements 

In [19]:
import numpy as np

array=np.array([[1,3,4,8,7],
                [2,3,4,5,5]])
print("maximum value of elements:",np.max(array))
print("minimum value of elements:",np.min(array))
print("minimum value of index element:",np.argmin(array))
print("miximum value of index element:",np.argmax(array))



maximum value of elements: 8
minimum value of elements: 1
minimum value of index element: 0
miximum value of index element: 3


# sum across coloumn and rows

In [24]:
import numpy as np

array=np.array([[1,3,4,8,7],
                [2,3,4,5,5]])

print("Coloum wise sum:",np.sum(array, axis=0))
print("Row wise sum:",np.sum(array, axis=1))

Coloum wise sum: [ 3  6  8 13 12]
Row wise sum: [23 19]


### product of elements

In [25]:
import numpy as np

array=np.array([[1,3,4,8,7],
                [2,3,4,5,5]])

print("Product of all elements:",np.prod(array))

Product of all elements: 403200


## array size

In [26]:
import numpy as np

array=np.array([[1,3,4,8,7],
                [2,3,4,5,5]])

print(array.size)

10


## Random array creation

In [27]:
rand_array= np.random.randint(1,1000, size=7)
print(rand_array)

[722 787 403 274 226 624 856]


## Reshape

### change array shape eg 23 to 32.this single dimension array only coloums


In [28]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


## Flaten 
### convert to multi dimensional array to 1D

In [ ]:
import numpy as np

arr=np.array([[1,2,3],[1,4,6]])
flat=arr.flatten()
print(flat)


[1 2 3 1 4 6]


## Ravel
### same as flatten

In [30]:
import numpy as np

arr=np.array([[1,2,3],[1,4,6]])
raveld=arr.ravel()
print(raveld)

[1 2 3 1 4 6]


## Transpose
### rows to coloumn change 

In [32]:
import numpy as np

arr=np.array([[1,2,3],[1,4,6]])
transposed=arr.transpose()
print(transposed)

[[1 1]
 [2 4]
 [3 6]]


## Vstack and Hstack
### row wise and coloumn wise adding

In [33]:
import numpy as np

a=np.array([1,2,3])
b=np.array([1,4,6])

vertical = np.vstack((a, b))
horizontal = np.hstack((a, b))
print("vstack():\n", vertical)
print("hstack():", horizontal)

vstack():
 [[1 2 3]
 [1 4 6]]
hstack(): [1 2 3 1 4 6]


## Split 
#### split array into multiple array

In [35]:
arr = np.array([10, 20, 30, 40, 50, 60])
parts = np.split(arr, 3)
print(parts)

[array([10, 20]), array([30, 40]), array([50, 60])]


## Unique
### unique elements only print in array

In [36]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_values = np.unique(arr)
print(unique_values)

[1 2 3 4 5]


## Numpy filtering


In [37]:
import numpy as np

array = np.array([[50, 60, 40, 89, 90],
                  [89, 78, 56, 75, 99]])

marks = array[array > 40]
print("All marks > 40:", marks)  

All marks > 40: [50 60 89 90 89 78 56 75 99]


In [38]:
import numpy as np

array = np.array([[50, 60, 40, 89, 90],
                  [89, 78, 56, 75, 99]])

new_marks = array[(array > 40) & (array < 90)]
print("Marks between 40 and 90:", new_marks)  

Marks between 40 and 90: [50 60 89 89 78 56 75]


In [39]:
import numpy as np

array = np.array([[50, 60, 40, 89, 90],
                  [89, 78, 56, 75, 99]])

new_marks = array[(array > 40) | (array < 90)]
print("Marks between 40 and 90:", new_marks)  

Marks between 40 and 90: [50 60 40 89 90 89 78 56 75 99]


In [40]:
import numpy as np

array = np.array([[50, 60, 40, 89, 90],
                  [89, 78, 56, 75, 99]])

updated_marks = array[~(array < 40)]
print(updated_marks)

[50 60 40 89 90 89 78 56 75 99]
