# NUMPY

### Numpy multiplication

In [5]:
import numpy as np

lst = [2, 4, 6]

array = np.array(lst)
result = array * 2

print(result)




[ 4  8 12]


### Numpy addition


In [ ]:
import numpy as np

lst=[2,4,5]
lst1=[2,4,5]
array1=np.array(lst)
array2=np.array(lst1)
result=array1+array2
print(result) 

[ 4  8 10]


### Numpy Substraction


In [8]:
import numpy as np

lst=[2,3,5]
lst1=[2,4,5]
array1=np.array(lst)
array2=np.array(lst1)
result=array1-array2
print(result)


[ 0 -1  0]


### Numpy division

In [9]:
import numpy as np


lst = [2, 4, 6]

array = np.array(lst)
result = array//2

print(result)


[1 2 3]


# Scalar arithmetic operation

In [ ]:
import numpy as np

#Mathematical operation in a single line

array=np.array([1,2,3,4,5])

print(array+1)
print(array-1)
print(array//1)
print(array*2)
print(array**2)
print(array**3)


[2 3 4 5 6]
[0 1 2 3 4]
[1 2 3 4 5]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[  1   8  27  64 125]


# Vector Arithmetic operation

In [16]:
import numpy as np


array = np.array([1,2,3,4,5])
array1=np.array([1.2,2.2,3.3,4.4,5.6])
print(np.sqrt(array))
print(np.round(array1))
print(np.floor(array1))
print(np.pi)


[1.         1.41421356 1.73205081 2.         2.23606798]
[1. 2. 3. 4. 6.]
[1. 2. 3. 4. 5.]
3.141592653589793


# matrice multiplication

### 2D Array

In [ ]:
import numpy as np

A=np.array([[1,2],
            [2,3]])

B=np.array([[2,3],
            [7,8]])

print(A.shape)#array dimension
print(A*B)

(2, 2)
[[ 2  6]
 [14 24]]


# indexing

## index value number

In [21]:
lst=[[[1,2,3],[2,4,5],[3,4,5]]]
print(lst[0][1][1])

4


In [28]:
import numpy as np

lst = np.array([[[1, 2, 3],
                 [2, 4, 5],
                 [3, 4, 5]]])

print(lst[0][0])

[1 2 3]


# index dimension check

In [30]:
import numpy as np

lst = np.array([[[1, 2, 3],
                 [2, 4, 5],
                 [3, 4, 5]]])

print(lst.ndim)

3


In [31]:
import numpy as np

lst = np.array([[[1, 2, 3],
                 [2, 4, 5],
                 [3, 4, 5]]])

print(lst.shape)

(1, 3, 3)


# Addition

In [36]:
import numpy as np

lst = np.array([[[1, 2, 3],
                 [2, 4, 5],
                 [3, 4, 5]]])

print(lst[0]+[1])

[[2 3 4]
 [3 5 6]
 [4 5 6]]


# 3D multiplication nested list

In [40]:
import numpy as np

lst=[[1,2,3],[3,4,5],[4,5,6]]
result=np.array(lst)
result=result*5
print(result)

[[ 5 10 15]
 [15 20 25]
 [20 25 30]]


In [41]:
import numpy as np

lst=[[1,2,3],[3,4,5],[4,5,6]]

result=np.array(lst)
print(lst[0]+lst[1])



[1, 2, 3, 3, 4, 5]


# slice


In [55]:
import numpy as np

lst=[1,2,3,4,5,6,7,8]
result=np.array(lst)

print(lst[1:8])

[2, 3, 4, 5, 6, 7, 8]


In [48]:
import numpy as np

lst=[1,2,3,4,5,6,7,8]
result=np.array(lst)

print(lst[1:])

[2, 3, 4, 5, 6, 7, 8]


In [51]:
import numpy as np

lst=[1,2,3,4,5,6,7,8]
result=np.array(lst)

print(lst[:-1])

[1, 2, 3, 4, 5, 6, 7]


# Negative slicing

In [53]:
import numpy as np

lst=np.array([1,2,3,4,5,6,7,8])
print(lst[-3:-1])


[6 7]


# print every 3rd element


In [54]:
import numpy as np

lst=np.array([1,2,3,4,5,6,7,7])
print(lst[::3])

[1 4 7]


# slicing 2D

## Row slicing

In [56]:
import numpy as np

lst=np.array([[1,2,3,4,5,6,7],
              [2,4,5,6,7,8,8]])

print(lst[0,0:4])



[1 2 3 4]


## coloumn slicing

In [57]:
import numpy as np

lst=np.array([[1,2,3,4,5,6,7],
              [2,4,5,6,7,8,8]])

print(lst[0:2,1])


[2 4]


In [61]:
import numpy as np
lst=np.array([[1,2,3,4,5,6,7],
              [2,4,5,6,7,8,8]])

print(lst[0:2, 1:4])



[[2 3 4]
 [4 5 6]]
