# problems

## 1D slicing

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[2:5])

[30 40 50]


In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[3:])

[40 50 60 70 80]


In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[:4])

[10 20 30 40]


## Negative slicing

In [5]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35])
print(arr[-3:])

[25 30 35]


In [7]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35])
print(arr[-3:-1])

[25 30]


## Step slicing

In [9]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30, 35])
print(arr[::2])

[ 5 15 25 35]


In [10]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30, 35])
print(arr[1::3])

[10 25]
